packages:
  - apps/*
  - packages/*
ignoredBuiltDependencies:
  - esbuild
  - sharp
  - workerd
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - better-sqlite3
  - core-js
  - msw
  - protobufjs
  - unrs-resolver
patchedDependencies:
  wrangler@4.42.0: patches/wrangler@4.42.0.patch
