import {type RouteConfig, index, route} from '@react-router/dev/routes';

export default [
  index('routes/home.tsx'),
  route('search', 'routes/search.tsx'),
  route('movies/:id', 'routes/movies.$id.tsx'),
  route('daily', 'routes/daily.tsx'),
  route('weekly', 'routes/weekly.tsx'),
  route('monthly', 'routes/monthly.tsx'),
  route('people', 'routes/people.tsx'),
  route('people/crossings', 'routes/people.crossings.tsx'),
  route('people/:id', 'routes/people.$id.tsx'),
  route('awards', 'routes/awards.tsx'),
  route('crossings', 'routes/crossings.tsx'),
  route('uncrowned', 'routes/uncrowned.tsx'),
  route('awards/:slug', 'routes/awards.$slug.tsx'),
  route('awards/:slug/:year', 'routes/awards.$slug.$year.tsx'),
  route('years', 'routes/years.tsx'),
  route('years/:year', 'routes/years.$year.tsx'),
  route('robots.txt', 'routes/robots.tsx'),
  route('feed.xml', 'routes/feed.tsx'),
  route('sitemap.xml', 'routes/sitemap-index.tsx'),
  route('sitemap/movies.xml', 'routes/sitemap-movies.tsx'),
  route('sitemap/awards.xml', 'routes/sitemap-awards.tsx'),
  route('sitemap/years.xml', 'routes/sitemap-years.tsx'),
  route('sitemap/people.xml', 'routes/sitemap-people.tsx'),
  route('quiz', 'routes/quiz.tsx'),
  route('quiz/poster.png', 'routes/quiz-poster.tsx'),
  route('og/movie.png', 'routes/og-movie.tsx'),
  route('og/person.png', 'routes/og-person.tsx'),
  route('og/home.png', 'routes/og-home.tsx'),
  route('og/banner.png', 'routes/og-banner.tsx'),
  route('og/quiz.png', 'routes/og-quiz.tsx'),
  route('admin/login', 'routes/admin.login.tsx'),
  route('admin/movies', 'routes/admin.movies.tsx'),
  route('admin/movies/:id', 'routes/admin.movies.$id.tsx'),
  route('admin/movies/selections', 'routes/admin.movies.selections.tsx'),
  route('admin/ceremonies', 'routes/admin.ceremonies.tsx'),
  route('admin/ceremonies/:uid', 'routes/admin.ceremonies.$uid.tsx'),
] satisfies RouteConfig;
