name = "shine-scrapers"
main = "src/index.ts"
compatibility_date = "2025-03-26"
compatibility_flags = ["nodejs_compat"]

[env.development]
vars = { TURSO_DATABASE_URL = "libsql://shine-dlwr.aws-ap-northeast-1.turso.io" }

[vars]
# For production, use wrangler secret for sensitive values
# TURSO_DATABASE_URL = ""
# TURSO_AUTH_TOKEN = ""
