name = "shine-scrapers"
main = "src/index.ts"
compatibility_date = "2025-03-26"
compatibility_flags = ["nodejs_compat"]

[env.development]
name = "shine-scrapers-dev"
vars = { TURSO_DATABASE_URL = "${TURSO_DATABASE_URL_DEV}" }
# TURSO_AUTH_TOKEN will be loaded from environment variables

[env.production]
name = "shine-scrapers-prod"
vars = { TURSO_DATABASE_URL = "${TURSO_DATABASE_URL_PROD}" }
# TURSO_AUTH_TOKEN should be set via: wrangler secret put TURSO_AUTH_TOKEN --env production

[vars]
# Default environment (fallback to development)
TURSO_DATABASE_URL = "${TURSO_DATABASE_URL_DEV}"
