import {
  japanAcademy,
  kinemaJunpo,
  mainichi,
  blueRibbon,
  hochi,
  yokohama,
  nikkanSports,
} from './organizations';
import type {PersonAwardDefinition} from './types';

export const japanesePersonAwardDefinitions: PersonAwardDefinition[] = [
  {
    slug: 'japan-academy-director',
    ...japanAcademy,
    categoryNames: ['監督賞'],
    name: '最優秀監督賞',
    description:
      '日本アカデミー賞 最優秀監督賞の歴代受賞者と優秀監督賞ノミネートの一覧。',
    role: 'director',
  },
  {
    slug: 'japan-academy-lead-actor',
    ...japanAcademy,
    categoryNames: ['主演男優賞'],
    name: '最優秀主演男優賞',
    description:
      '日本アカデミー賞 最優秀主演男優賞の歴代受賞者と優秀主演男優賞ノミネートの一覧。',
    role: 'actor',
  },
  {
    slug: 'japan-academy-lead-actress',
    ...japanAcademy,
    categoryNames: ['主演女優賞'],
    name: '最優秀主演女優賞',
    description:
      '日本アカデミー賞 最優秀主演女優賞の歴代受賞者と優秀主演女優賞ノミネートの一覧。',
    role: 'actor',
  },
  {
    slug: 'japan-academy-supporting-actor',
    ...japanAcademy,
    categoryNames: ['助演男優賞'],
    name: '最優秀助演男優賞',
    description:
      '日本アカデミー賞 最優秀助演男優賞の歴代受賞者と優秀助演男優賞ノミネートの一覧。',
    role: 'actor',
  },
  {
    slug: 'japan-academy-supporting-actress',
    ...japanAcademy,
    categoryNames: ['助演女優賞'],
    name: '最優秀助演女優賞',
    description:
      '日本アカデミー賞 最優秀助演女優賞の歴代受賞者と優秀助演女優賞ノミネートの一覧。',
    role: 'actor',
  },
  {
    slug: 'kinema-junpo-director',
    ...kinemaJunpo,
    categoryNames: ['日本映画監督賞'],
    name: '日本映画監督賞',
    description:
      'キネマ旬報 日本映画監督賞の歴代受賞者の一覧。1955年度に創設。',
    role: 'director',
  },
  {
    slug: 'kinema-junpo-lead-actor',
    ...kinemaJunpo,
    categoryNames: ['主演男優賞'],
    name: '主演男優賞',
    description: 'キネマ旬報 主演男優賞の歴代受賞者の一覧。',
    role: 'actor',
  },
  {
    slug: 'kinema-junpo-lead-actress',
    ...kinemaJunpo,
    categoryNames: ['主演女優賞'],
    name: '主演女優賞',
    description: 'キネマ旬報 主演女優賞の歴代受賞者の一覧。',
    role: 'actor',
  },
  {
    slug: 'kinema-junpo-supporting-actor',
    ...kinemaJunpo,
    categoryNames: ['助演男優賞'],
    name: '助演男優賞',
    description: 'キネマ旬報 助演男優賞の歴代受賞者の一覧。',
    role: 'actor',
  },
  {
    slug: 'kinema-junpo-supporting-actress',
    ...kinemaJunpo,
    categoryNames: ['助演女優賞'],
    name: '助演女優賞',
    description: 'キネマ旬報 助演女優賞の歴代受賞者の一覧。',
    role: 'actor',
  },
  {
    slug: 'kinema-junpo-foreign-director',
    ...kinemaJunpo,
    categoryNames: ['外国映画監督賞'],
    name: '外国映画監督賞',
    description:
      'キネマ旬報 外国映画監督賞の歴代受賞者の一覧。外国映画ベスト・テンと同じ年度に選ばれる外国映画の監督賞。',
    role: 'director',
  },
  {
    slug: 'mainichi-director',
    ...mainichi,
    categoryNames: ['監督賞'],
    name: '監督賞',
    description: '毎日映画コンクール 監督賞の歴代受賞者の一覧。',
    role: 'director',
  },
  {
    slug: 'mainichi-lead-actor',
    ...mainichi,
    categoryNames: ['男優主演賞'],
    name: '男優主演賞',
    description:
      '毎日映画コンクール 男優主演賞の歴代受賞者の一覧。第17回までの男優演技賞を含む。2023年を最後に主演俳優賞へ統合された。',
    role: 'actor',
  },
  {
    slug: 'mainichi-lead-actress',
    ...mainichi,
    categoryNames: ['女優主演賞'],
    name: '女優主演賞',
    description:
      '毎日映画コンクール 女優主演賞の歴代受賞者の一覧。第17回までの女優演技賞を含む。2023年を最後に主演俳優賞へ統合された。',
    role: 'actor',
  },
  {
    slug: 'mainichi-supporting-actor',
    ...mainichi,
    categoryNames: ['男優助演賞'],
    name: '男優助演賞',
    description:
      '毎日映画コンクール 男優助演賞の歴代受賞者の一覧。2023年を最後に助演俳優賞へ統合された。',
    role: 'actor',
  },
  {
    slug: 'mainichi-supporting-actress',
    ...mainichi,
    categoryNames: ['女優助演賞'],
    name: '女優助演賞',
    description:
      '毎日映画コンクール 女優助演賞の歴代受賞者の一覧。2023年を最後に助演俳優賞へ統合された。',
    role: 'actor',
  },
  {
    slug: 'mainichi-lead-performance',
    ...mainichi,
    categoryNames: ['主演俳優賞'],
    name: '主演俳優賞',
    description:
      '毎日映画コンクール 主演俳優賞の歴代受賞者の一覧。2024年に男優主演賞・女優主演賞を統合して新設された性別のない演技賞。',
    role: 'actor',
  },
  {
    slug: 'mainichi-supporting-performance',
    ...mainichi,
    categoryNames: ['助演俳優賞'],
    name: '助演俳優賞',
    description:
      '毎日映画コンクール 助演俳優賞の歴代受賞者の一覧。2024年に男優助演賞・女優助演賞を統合して新設された性別のない演技賞。',
    role: 'actor',
  },
  {
    slug: 'blue-ribbon-director',
    ...blueRibbon,
    categoryNames: ['監督賞'],
    name: '監督賞',
    description: 'ブルーリボン賞 監督賞の歴代受賞者の一覧。',
    role: 'director',
  },
  {
    slug: 'blue-ribbon-lead-actor',
    ...blueRibbon,
    categoryNames: ['主演男優賞'],
    name: '主演男優賞',
    description: 'ブルーリボン賞 主演男優賞の歴代受賞者の一覧。',
    role: 'actor',
  },
  {
    slug: 'blue-ribbon-lead-actress',
    ...blueRibbon,
    categoryNames: ['主演女優賞'],
    name: '主演女優賞',
    description: 'ブルーリボン賞 主演女優賞の歴代受賞者の一覧。',
    role: 'actor',
  },
  {
    slug: 'blue-ribbon-supporting-actor',
    ...blueRibbon,
    categoryNames: ['助演男優賞'],
    name: '助演男優賞',
    description: 'ブルーリボン賞 助演男優賞の歴代受賞者の一覧。',
    role: 'actor',
  },
  {
    slug: 'blue-ribbon-supporting-actress',
    ...blueRibbon,
    categoryNames: ['助演女優賞'],
    name: '助演女優賞',
    description: 'ブルーリボン賞 助演女優賞の歴代受賞者の一覧。',
    role: 'actor',
  },
  {
    slug: 'hochi-director',
    ...hochi,
    categoryNames: ['監督賞'],
    name: '監督賞',
    description: '報知映画賞 監督賞の歴代受賞者の一覧。1985年度に創設。',
    role: 'director',
  },
  {
    slug: 'hochi-lead-actor',
    ...hochi,
    categoryNames: ['主演男優賞'],
    name: '主演男優賞',
    description: '報知映画賞 主演男優賞の歴代受賞者の一覧。',
    role: 'actor',
  },
  {
    slug: 'hochi-lead-actress',
    ...hochi,
    categoryNames: ['主演女優賞'],
    name: '主演女優賞',
    description: '報知映画賞 主演女優賞の歴代受賞者の一覧。',
    role: 'actor',
  },
  {
    slug: 'hochi-supporting-actor',
    ...hochi,
    categoryNames: ['助演男優賞'],
    name: '助演男優賞',
    description: '報知映画賞 助演男優賞の歴代受賞者の一覧。',
    role: 'actor',
  },
  {
    slug: 'hochi-supporting-actress',
    ...hochi,
    categoryNames: ['助演女優賞'],
    name: '助演女優賞',
    description: '報知映画賞 助演女優賞の歴代受賞者の一覧。',
    role: 'actor',
  },
  {
    slug: 'yokohama-director',
    ...yokohama,
    categoryNames: ['監督賞'],
    name: '監督賞',
    description:
      'ヨコハマ映画祭 監督賞の歴代受賞者の一覧。1979年度の第1回から映画ファンが選出している。',
    role: 'director',
  },
  {
    slug: 'yokohama-lead-actor',
    ...yokohama,
    categoryNames: ['主演男優賞'],
    name: '主演男優賞',
    description: 'ヨコハマ映画祭 主演男優賞の歴代受賞者の一覧。',
    role: 'actor',
  },
  {
    slug: 'yokohama-lead-actress',
    ...yokohama,
    categoryNames: ['主演女優賞'],
    name: '主演女優賞',
    description: 'ヨコハマ映画祭 主演女優賞の歴代受賞者の一覧。',
    role: 'actor',
  },
  {
    slug: 'yokohama-supporting-actor',
    ...yokohama,
    categoryNames: ['助演男優賞'],
    name: '助演男優賞',
    description: 'ヨコハマ映画祭 助演男優賞の歴代受賞者の一覧。',
    role: 'actor',
  },
  {
    slug: 'yokohama-supporting-actress',
    ...yokohama,
    categoryNames: ['助演女優賞'],
    name: '助演女優賞',
    description: 'ヨコハマ映画祭 助演女優賞の歴代受賞者の一覧。',
    role: 'actor',
  },
  {
    slug: 'nikkan-sports-director',
    ...nikkanSports,
    categoryNames: ['監督賞'],
    name: '監督賞',
    description:
      '日刊スポーツ映画大賞 監督賞の歴代受賞者の一覧。1988年度に創設。',
    role: 'director',
  },
  {
    slug: 'nikkan-sports-lead-actor',
    ...nikkanSports,
    categoryNames: ['主演男優賞'],
    name: '主演男優賞',
    description: '日刊スポーツ映画大賞 主演男優賞の歴代受賞者の一覧。',
    role: 'actor',
  },
  {
    slug: 'nikkan-sports-lead-actress',
    ...nikkanSports,
    categoryNames: ['主演女優賞'],
    name: '主演女優賞',
    description: '日刊スポーツ映画大賞 主演女優賞の歴代受賞者の一覧。',
    role: 'actor',
  },
  {
    slug: 'nikkan-sports-supporting-actor',
    ...nikkanSports,
    categoryNames: ['助演男優賞'],
    name: '助演男優賞',
    description: '日刊スポーツ映画大賞 助演男優賞の歴代受賞者の一覧。',
    role: 'actor',
  },
  {
    slug: 'nikkan-sports-supporting-actress',
    ...nikkanSports,
    categoryNames: ['助演女優賞'],
    name: '助演女優賞',
    description: '日刊スポーツ映画大賞 助演女優賞の歴代受賞者の一覧。',
    role: 'actor',
  },
];
