name = "shine-database-proxy"
main = "src/database-proxy.ts"
compatibility_date = "2025-03-26"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "shine-main"
database_id = "ef1ae873-1ab5-4b99-aa60-9673857c0974"

[observability.logs]
enabled = true
