name = "shine-api"
main = "src/index.ts"
compatibility_date = "2025-03-26"
compatibility_flags = ["nodejs_compat"]

[vars]
# Set these in .dev.vars for local development
# TURSO_DATABASE_URL = ""
# TURSO_AUTH_TOKEN = ""
