name: Fix Dependabot Lockfile

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  fix-lockfile:
    # Only run on Dependabot PRs
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Check if lockfile needs update
        id: lockfile-check
        run: |
          if pnpm install --frozen-lockfile 2>/dev/null; then
            echo "needs_update=false" >> $GITHUB_OUTPUT
            echo "Lockfile is up to date"
          else
            echo "needs_update=true" >> $GITHUB_OUTPUT
            echo "Lockfile needs update"
          fi

      - name: Update lockfile
        if: steps.lockfile-check.outputs.needs_update == 'true'
        run: |
          echo "Updating lockfile..."
          pnpm install
          
      - name: Commit lockfile update
        if: steps.lockfile-check.outputs.needs_update == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          if git diff --quiet pnpm-lock.yaml; then
            echo "No lockfile changes to commit"
          else
            git add pnpm-lock.yaml
            git commit -m "chore: update pnpm-lock.yaml

            🤖 Automated lockfile update for Dependabot PR
            
            Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>"
            git push
            echo "Lockfile updated and pushed"
          fi

      - name: Verify CI will pass
        if: steps.lockfile-check.outputs.needs_update == 'true'
        run: |
          echo "Verifying updated lockfile..."
          pnpm install --frozen-lockfile
          echo "✅ Lockfile verification successful"